brew "roll"      # dice roller

cask "1password"
cask "iterm2"    # better terminal
cask "discord"
cask "zoom"
cask "zulu@21"   # JDK

# gaming stuff
cask "nvidia-geforce-now"
cask "steam"

mas "Affinity Publisher 2", id: 1606941598
mas "Kindle", id: 405399194
mas "Keynote", id: 409183694
mas "HP Easy Scan", id: 967004861
mas "Slack", id: 803453959
